/* ISC license. */

/* Generated by: ./configure --with-sysdeps=/home/U00P3505/projects/skarnet/skalibs-2.4.0.0/../sysdeps --prefix=/home/U00P3505/usr --disable-shared */

#ifndef SKALIBS_CONFIG_H
#define SKALIBS_CONFIG_H

#define SKALIBS_VERSION "2.4.0.0"
#define SKALIBS_DEFAULTPATH "/usr/bin:/bin"
#define SKALIBS_ETC "/etc"
#define SKALIBS_SPROOT ""
#define SKALIBS_HOME ""
#undef SKALIBS_FLAG_REPLACE_LIBC
#undef SKALIBS_FLAG_CLOCKISTAI
#undef SKALIBS_FLAG_USERT
#undef SKALIBS_FLAG_USEMON
#define SKALIBS_FLAG_WANTIPV6
#undef SKALIBS_FLAG_PREFERSELECT

#endif
